### ISSUE TITLE
Link to website/repos 

### ISSUE THREAD

**Issue by traversaro** [ryanbgriffiths/ICRA2024PaperList#1]
Thanks @ryanbgriffiths , this repo is quite useful! I was wondering if do you think it could make sense to add a link to the website/repo for paper that have it (I was interesting in adding https://github.com/ami-iit/paper_bergonti_2024_icra_codesign-morphing-drones, fyi @FabioBergonti). I guess the link could be added to the title, so that it is not necessary to change the README structure.

If you are not interested, feel free to close the issue, thanks again!

**Comment by ryanbgriffiths** [comment]
That is a good idea. 

However it would be a lot of work to manually add these. I could add a link in the cases were it is provided in the abstract of the paper which should be easy enough. 

I can add the link in your case and I might add a note saying if anyone wants to add a link to a page send a pull request or something.

**Comment by traversaro** [comment]
See https://github.com/ryanbgriffiths/ICRA2024PaperList/pull/2 for example.

**Comment by traversaro** [comment]
> That is a good idea.
> 
> However it would be a lot of work to manually add these. I could add a link in the cases were it is provided in the abstract of the paper which should be easy enough.
> 
> I can add the link in your case and I might add a note saying if anyone wants to add a link to a page send a pull request or something.

Sure, I was actually interested in just adding the one mentioned, and let interested people add them.
