### ISSUE TITLE
The paper download site cannot be opened

### ISSUE THREAD

**Issue by yxqsheep** [ryanbgriffiths/ICRA2024PaperList#6]
It's a very useful repo, thanks a lot! But I can't open the paper download site https://r2.infovaya.com/ICRA24-Proc-Part1-V1.zip (The website is displayed as follows). Is there something wrong?
![](https://github.com/ryanbgriffiths/ICRA2024PaperList/assets/57320970/85b61da6-b325-47f0-90f2-abd803cd8131)

**Comment by FengyuGuo** [comment]
same problem

**Comment by Ian-YJX** [comment]
same promblem

**Comment by redfish9** [comment]
same problem

**Comment by DoongLi** [comment]
This link seems to be dead due to the end of ICRA 2024, someone saved the proceedings can share？

**Comment by Cheng909865905** [comment]
这些论文都是中了还是所有投稿的论文（包括没中）啊

**Comment by DoongLi** [comment]
@Cheng909865905 这些都是中稿的论文，实际上 好像没有办法查看所有投稿的论文~

**Comment by DoongLi** [comment]
Hi, everyone, you can now view all the papers from ICRA 2024 on the IEEE website.  https://ieeexplore.ieee.org/xpl/conhome/10609961/proceeding  @FengyuGuo @yxqsheep @redfish9 @Cheng909865905 @
